### DISCUSSION TITLE
Ability to ignore files

### DISCUSSION THREAD

**Discussion by jeffschnellerEnvisa** [montudor/action-zip#14] [Q&A] [answered]
Is there a way to ignore files to zip?

**Comment by montudor** [comment, marked as answer]
Yes, it works exactly like the actual linux command, for example:
```yml
- uses: montudor/action-zip@v0.1.1
  with:
    args: zip -r dir.zip ./dir -x '*.git*'
```
would exclude the `.git` folder.
