### DISCUSSION TITLE
How do I zip contents of current directory to root of archive

### DISCUSSION THREAD

**Discussion by kbocock-krg** [montudor/action-zip#25] [Help wanted]
So far I have tried:

-r -j <zip filename> and the following items (. , ./, ./*, *, **.*,*.*, current folder name/*) none of them work. Please help.

**Comment by montudor** [comment]
I believe you may be looking for this:

```bash
zip -r archive.zip *
```

Here is it used in an action:
```yaml
- name: Install zip
  uses: montudor/action-zip@v1

- name: Zip output
  run: zip -r archive.zip *
  working-directory: path/to/work-dir
```
