### ISSUE TITLE
zip error: Nothing to do!

### ISSUE THREAD

**Issue by teocns** [montudor/action-zip#19]
I have a project dir like so:

```

└── lambda
    └── lambda_handler.py

```

WIth .yml file instructions like:
```

 steps:
      - name: zip
        uses: montudor/action-zip@v0.1.0
        with:
          args:   zip -qq -r bundle.zip lambda


```
I keep receiving the following error: 

`zip error: Nothing to do! (try: zip -qq -r bundle.zip . -i lambda/)`

I have also tried with `zip -qq -r bundle.zip . -i lambda/` but it would just result in an empty zip.
