### ISSUE TITLE
zip error: Nothing to do!

### ISSUE THREAD

**Issue by FrenkyDema** [montudor/action-zip#28]
As in the Issue #19, the problem reappears but the difference is the version of checkout (V3)

WIth .yml file instructions like:

```yml
    steps:
      - uses: actions/checkout@v3

      - name: Create Archive
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r archive.zip directory/* -x "directory/test.bat"
```
I keep receiving the following error:
```
zip error: Nothing to do! (texture-pack.zip)
```
