### ISSUE TITLE
"Zipping a folder from a different work dir" example not using zip from action

### ISSUE THREAD

**Issue by dannystaple** [montudor/action-zip#33]
The "Zipping a folder from a different work dir" example, in the README.md doesn't make use of the zip tool inside the container, and uses the zip tool that may or may not be installed in the job container image. The default github container has a zip tool installed, but use of other containers (for build tools etc) mean that may be missing.

Eg:

```yaml
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:7.0-jammy
```
